force-app/main/default/objects/sfcraft_LogConfig__mdt/sfcraft_LogConfig__mdt.object-meta.xml
<CustomObject>
    <label>SfCraft Log Config</label>
    <pluralLabel>SfCraft Log Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/sfcraft_LogConfig__mdt/fields/sfcraft_DetailsField__c.field-meta.xml
<CustomField>
    <fullName>sfcraft_DetailsField__c</fullName>
    <description>A field to store various details like stacktrace. Must be long text</description>
    <label>Details Field</label>
    <metadataRelationshipControllingField>sfcraft_LogConfig__mdt.sfcraft_LogObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>sfcraft Log Configs details</relationshipLabel>
    <relationshipName>sfcraft_LogConfigsDetails</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/sfcraft_LogConfig__mdt/fields/sfcraft_IsActive__c.field-meta.xml
<CustomField>
    <fullName>sfcraft_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the config is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sfcraft_LogConfig__mdt/fields/sfcraft_LogObject__c.field-meta.xml
<CustomField>
    <fullName>sfcraft_LogObject__c</fullName>
    <description>Stores name of the log object</description>
    <label>Log Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>sfcraft_LogConfigs</relationshipLabel>
    <relationshipName>sfcraft_LogConfigs</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/sfcraft_LogConfig__mdt/fields/sfcraft_MessageField__c.field-meta.xml
<CustomField>
    <fullName>sfcraft_MessageField__c</fullName>
    <description>Field to store short messages. Must be 255 chars long</description>
    <label>Message Field</label>
    <metadataRelationshipControllingField>sfcraft_LogConfig__mdt.sfcraft_LogObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>SfCraft_Log_Configs message</relationshipLabel>
    <relationshipName>sfcraft_LogConfigsMessage</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/sfcraft_LogConfig__mdt/fields/sfcraft_ScopeField__c.field-meta.xml
<CustomField>
    <fullName>sfcraft_ScopeField__c</fullName>
    <description>Field to store scope, e.g. class + method. Must be text</description>
    <label>Scope Field</label>
    <metadataRelationshipControllingField>sfcraft_LogConfig__mdt.sfcraft_LogObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>SfCraft_Log_Configs Scope</relationshipLabel>
    <relationshipName>sfcraft_LogConfigsScope</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/sfcraft_LogConfig__mdt/fields/sfcraft_SeverityField__c.field-meta.xml
<CustomField>
    <fullName>sfcraft_SeverityField__c</fullName>
    <description>Field to store severity. Must be text</description>
    <label>Severity Field</label>
    <metadataRelationshipControllingField>sfcraft_LogConfig__mdt.sfcraft_LogObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>SfCraft_Log_Configs Severity</relationshipLabel>
    <relationshipName>sfcraft_LogConfigsSeverity</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/src/classes/sfcraft_LogConfig.cls
public without sharing class sfcraft_LogConfig {
    private sfcraft_LogConfig__mdt config;

    private SObjectType sobjType;

    public sfcraft_LogConfig() {
        List<sfcraft_LogConfig__mdt> configs = [
            SELECT sfcraft_LogObject__c, sfcraft_DetailsField__c, sfcraft_MessageField__c, sfcraft_ScopeField__c,
                sfcraft_SeverityField__c
            FROM sfcraft_LogConfig__mdt
            WHERE sfcraft_IsActive__c = true
            LIMIT 1
        ];
        if (configs.isEmpty()) {
            throw new IllegalArgumentException(
                'No active log config found, please create sfcraft_LogConfig__mdt record'
            );
        }
        this.config = configs.get(0);
    }

    public String getDetailsFieldName() {
        return this.config.sfcraft_DetailsField__c;
    }

    public String getMessageFieldName() {
        return this.config.sfcraft_MessageField__c;
    }

    public String getScopeFieldName() {
        return this.config.sfcraft_ScopeField__c;
    }

    public String getSeverityFieldName() {
        return this.config.sfcraft_SeverityField__c;
    }

    public SObjectType getLogSObjectType() {
        if (null == this.sobjType) {
            String sobjTypeName = this.config.sfcraft_LogObject__c;
            this.sobjType = Schema.getGlobalDescribe().get(sobjTypeName);
        }
        return this.sobjType;
    }
}